Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(wandb_model_trainer.py:1598247): Gdk-CRITICAL **: 09:16:00.247: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
wandb: Agent Starting Run: vdclvnxi with config:
wandb: 	batch_size: 124
wandb: 	criterion: cross_entropy
wandb: 	epochs: 150
wandb: 	learning_rate: 0.1
wandb: 	model_name: cifar10_mobilenetv2_x1_0
wandb: 	momentum: 0.9
wandb: 	optimizer: nesterov
wandb: 	pretrained: False
wandb: 	scheduler: Cosine Annealing
wandb: 	transformation: U
wandb: 	use_SAM: True
wandb: 	weight_decay: 1e-05
wandb: Currently logged in as: naddeok (use `wandb login --relogin` to force relogin)
CIFAR10 is Loaded
Create sweep with ID: ta5aglp3
Sweep URL: https://wandb.ai/naddeok/CIFAR10/sweeps/ta5aglp3
2021-05-18 09:16:03.963051: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-18 09:16:03.965712: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
wandb: Tracking run with wandb version 0.10.30
wandb: Syncing run colorful-sweep-1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/naddeok/CIFAR10
wandb: üßπ View sweep at https://wandb.ai/naddeok/CIFAR10/sweeps/ta5aglp3
wandb: üöÄ View run at https://wandb.ai/naddeok/CIFAR10/runs/vdclvnxi
wandb: Run data is saved locally in /home/naddeok5/FIM/wandb/run-20210518_091602-vdclvnxi
wandb: Run `wandb offline` to turn off syncing.
Using cache found in /home/naddeok5/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
wandb: Waiting for W&B process to finish, PID 1598401
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb:                                                                                
wandb: Find user logs for this run at: /home/naddeok5/FIM/wandb/run-20210518_091602-vdclvnxi/logs/debug.log
wandb: Find internal logs for this run at: /home/naddeok5/FIM/wandb/run-20210518_091602-vdclvnxi/logs/debug-internal.log
wandb: Run summary:
wandb:   Data Augmentation False
wandb:            _runtime 3
wandb:          _timestamp 1621343765
wandb:               _step 0
wandb: Run history:
wandb:   Data Augmentation ‚ñÅ
wandb:            _runtime ‚ñÅ
wandb:          _timestamp ‚ñÅ
wandb:               _step ‚ñÅ
wandb: 
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced colorful-sweep-1: https://wandb.ai/naddeok/CIFAR10/runs/vdclvnxi
Run vdclvnxi errored: RuntimeError('CUDA error: out of memory')
wandb: ERROR Run vdclvnxi errored: RuntimeError('CUDA error: out of memory')
wandb: Sweep Agent: Waiting for job.
wandb: Sweep Agent: Exiting.

signal only works in main thread

