Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(wandb_model_trainer.py:3275588): Gdk-CRITICAL **: 21:47:46.878: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
wandb: Agent Starting Run: rejckqn0 with config:
wandb: 	batch_size: 256
wandb: 	criterion: cross_entropy
wandb: 	epochs: 300
wandb: 	learning_rate: 0.1
wandb: 	model_name: cifar10_resnet56
wandb: 	momentum: 0.9
wandb: 	optimizer: adadelta
wandb: 	pretrained: False
wandb: 	scheduler: Cosine Annealing
wandb: 	transformation: U
wandb: 	use_SAM: True
wandb: 	weight_decay: 0.0005
wandb: Currently logged in as: naddeok (use `wandb login --relogin` to force relogin)
CIFAR10 is Loaded
Create sweep with ID: nshswmr1
Sweep URL: https://wandb.ai/naddeok/ResNet%20CIFAR10/sweeps/nshswmr1
2021-05-13 21:47:50.434532: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-13 21:47:50.436587: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
wandb: Tracking run with wandb version 0.10.30
wandb: Syncing run usual-sweep-1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/naddeok/ResNet%20CIFAR10
wandb: üßπ View sweep at https://wandb.ai/naddeok/ResNet%20CIFAR10/sweeps/nshswmr1
wandb: üöÄ View run at https://wandb.ai/naddeok/ResNet%20CIFAR10/runs/rejckqn0
wandb: Run data is saved locally in /home/naddeok5/FIM/wandb/run-20210513_214748-rejckqn0
wandb: Run `wandb offline` to turn off syncing.

signal only works in main thread
Using cache found in /home/naddeok5/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Epoch:  1 	Train Loss:  0.0090846040391922 	Val Loss:  0.00919756817817688
Epoch:  11 	Train Loss:  0.009017475018501283 	Val Loss:  0.009195736908912658
Epoch:  21 	Train Loss:  0.00834524561405182 	Val Loss:  0.00856513557434082
