Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(wandb_model_trainer.py:1601722): Gdk-CRITICAL **: 09:22:11.462: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 4ash73lp with config:
wandb: 	batch_size: 124
wandb: 	criterion: cross_entropy
wandb: 	epochs: 150
wandb: 	learning_rate: 0.1
wandb: 	model_name: cifar10_mobilenetv2_x1_0
wandb: 	momentum: 0.9
wandb: 	optimizer: nesterov
wandb: 	pretrained: False
wandb: 	scheduler: Cosine Annealing
wandb: 	transformation: U
wandb: 	use_SAM: True
wandb: 	weight_decay: 1e-05
wandb: Currently logged in as: naddeok (use `wandb login --relogin` to force relogin)
CIFAR10 is Loaded
Create sweep with ID: rvtwmti9
Sweep URL: https://wandb.ai/naddeok/CIFAR10/sweeps/rvtwmti9
2021-05-18 09:22:41.207647: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-18 09:22:41.209868: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
wandb: Tracking run with wandb version 0.10.30
wandb: Syncing run glamorous-sweep-1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/naddeok/CIFAR10
wandb: üßπ View sweep at https://wandb.ai/naddeok/CIFAR10/sweeps/rvtwmti9
wandb: üöÄ View run at https://wandb.ai/naddeok/CIFAR10/runs/4ash73lp
wandb: Run data is saved locally in /home/naddeok5/FIM/wandb/run-20210518_092239-4ash73lp
wandb: Run `wandb offline` to turn off syncing.

signal only works in main thread
Using cache found in /home/naddeok5/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Epoch:  1 	Train Loss:  0.0156290131521225 	Val Loss:  0.006164168453216553
Epoch:  11 	Train Loss:  0.005834259087443352 	Val Loss:  0.00459880376458168
