Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(wandb_model_trainer.py:1597222): Gdk-CRITICAL **: 09:15:36.263: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
wandb: Agent Starting Run: ysspewcz with config:
wandb: 	batch_size: 124
wandb: 	criterion: cross_entropy
wandb: 	epochs: 150
wandb: 	learning_rate: 0.1
wandb: 	model_name: cifar10_mobilenetv2_x1_0
wandb: 	momentum: 0.9
wandb: 	optimizer: nesterov
wandb: 	pretrained: False
wandb: 	scheduler: Cosine Annealing
wandb: 	transformation: None
wandb: 	use_SAM: True
wandb: 	weight_decay: 1e-05
wandb: Currently logged in as: naddeok (use `wandb login --relogin` to force relogin)
CIFAR10 is Loaded
Create sweep with ID: 5iv1g2vo
Sweep URL: https://wandb.ai/naddeok/CIFAR10/sweeps/5iv1g2vo
2021-05-18 09:15:47.317058: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-18 09:15:47.319034: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
wandb: Tracking run with wandb version 0.10.30
wandb: Syncing run dandy-sweep-1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/naddeok/CIFAR10
wandb: üßπ View sweep at https://wandb.ai/naddeok/CIFAR10/sweeps/5iv1g2vo
wandb: üöÄ View run at https://wandb.ai/naddeok/CIFAR10/runs/ysspewcz
wandb: Run data is saved locally in /home/naddeok5/FIM/wandb/run-20210518_091545-ysspewcz
wandb: Run `wandb offline` to turn off syncing.

signal only works in main thread
Using cache found in /home/naddeok5/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Epoch:  1 	Train Loss:  0.013429229004383087 	Val Loss:  0.005636901009082794
Epoch:  11 	Train Loss:  0.0015083742599189282 	Val Loss:  0.0021436517655849456
Epoch:  21 	Train Loss:  0.0003668376024439931 	Val Loss:  0.002375531616806984
