Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(wandb_model_trainer.py:2021618): Gdk-CRITICAL **: 00:58:38.729: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
wandb: Agent Starting Run: tn2odr1o with config:
wandb: 	batch_size: 18
wandb: 	criterion: cross_entropy
wandb: 	epochs: 100
wandb: 	learning_rate: 0.021496184218062667
wandb: 	model_name: cifar10_mobilenetv2_x1_4
wandb: 	momentum: 0.9
wandb: 	optimizer: nesterov
wandb: 	pretrained: False
wandb: 	scheduler: Cosine Annealing
wandb: 	transformation: models/pretrained/U_w_means_0-005174736492335796_n0-0014449692098423839_n0-0010137659264728427_and_stds_1-130435824394226_1-128873586654663_1-1922636032104492_.pt
wandb: 	use_SAM: True
wandb: 	weight_decay: 1e-05
wandb: Currently logged in as: naddeok (use `wandb login --relogin` to force relogin)
Files already downloaded and verified
Files already downloaded and verified
CIFAR10 is Loaded
Create sweep with ID: 85hdflaz
Sweep URL: https://wandb.ai/naddeok/CIFAR10/sweeps/85hdflaz
2021-05-25 00:58:42.873899: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-25 00:58:42.876822: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
wandb: Tracking run with wandb version 0.10.30
wandb: Syncing run skilled-sweep-1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/naddeok/CIFAR10
wandb: üßπ View sweep at https://wandb.ai/naddeok/CIFAR10/sweeps/85hdflaz
wandb: üöÄ View run at https://wandb.ai/naddeok/CIFAR10/runs/tn2odr1o
wandb: Run data is saved locally in /home/naddeok5/FIM/wandb/run-20210525_005841-tn2odr1o
wandb: Run `wandb offline` to turn off syncing.
wandb: Waiting for W&B process to finish, PID 2021841
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.01MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.01MB uploaded (0.00MB deduped)wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: \ 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: | 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: / 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb:                                                                                
wandb: Find user logs for this run at: /home/naddeok5/FIM/wandb/run-20210525_005841-tn2odr1o/logs/debug.log
wandb: Find internal logs for this run at: /home/naddeok5/FIM/wandb/run-20210525_005841-tn2odr1o/logs/debug-internal.log
wandb: Run summary:
wandb:   Data Augmentation False
wandb:            _runtime 3
wandb:          _timestamp 1621918724
wandb:               _step 0
wandb: Run history:
wandb:   Data Augmentation ‚ñÅ
wandb:            _runtime ‚ñÅ
wandb:          _timestamp ‚ñÅ
wandb:               _step ‚ñÅ
wandb: 
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced skilled-sweep-1: https://wandb.ai/naddeok/CIFAR10/runs/tn2odr1o
Run tn2odr1o errored: RuntimeError('CUDA error: out of memory')
wandb: ERROR Run tn2odr1o errored: RuntimeError('CUDA error: out of memory')
wandb: Agent Starting Run: woy3c8cq with config:
wandb: 	batch_size: 21
wandb: 	criterion: cross_entropy
wandb: 	epochs: 100
wandb: 	learning_rate: 0.008557175290079586
wandb: 	model_name: cifar10_mobilenetv2_x1_4
wandb: 	momentum: 0.9
wandb: 	optimizer: nesterov
wandb: 	pretrained: False
wandb: 	scheduler: Cosine Annealing
wandb: 	transformation: models/pretrained/U_w_means_0-005174736492335796_n0-0014449692098423839_n0-0010137659264728427_and_stds_1-130435824394226_1-128873586654663_1-1922636032104492_.pt
wandb: 	use_SAM: True
wandb: 	weight_decay: 1e-05

signal only works in main thread

2021-05-25 00:58:49.719289: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-25 00:58:49.721377: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
wandb: Tracking run with wandb version 0.10.30
wandb: Syncing run eternal-sweep-2
wandb: ‚≠êÔ∏è View project at https://wandb.ai/naddeok/CIFAR10
wandb: üßπ View sweep at https://wandb.ai/naddeok/CIFAR10/sweeps/85hdflaz
wandb: üöÄ View run at https://wandb.ai/naddeok/CIFAR10/runs/woy3c8cq
wandb: Run data is saved locally in /home/naddeok5/FIM/wandb/run-20210525_005848-woy3c8cq
wandb: Run `wandb offline` to turn off syncing.
wandb: Waiting for W&B process to finish, PID 2022074
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: \ 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: | 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: / 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb:                                                                                
wandb: Find user logs for this run at: /home/naddeok5/FIM/wandb/run-20210525_005848-woy3c8cq/logs/debug.log
wandb: Find internal logs for this run at: /home/naddeok5/FIM/wandb/run-20210525_005848-woy3c8cq/logs/debug-internal.log
wandb: Run summary:
wandb:   Data Augmentation False
wandb:            _runtime 2
wandb:          _timestamp 1621918730
wandb:               _step 0
wandb: Run history:
wandb:   Data Augmentation ‚ñÅ
wandb:            _runtime ‚ñÅ
wandb:          _timestamp ‚ñÅ
wandb:               _step ‚ñÅ
wandb: 
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced eternal-sweep-2: https://wandb.ai/naddeok/CIFAR10/runs/woy3c8cq
Run woy3c8cq errored: RuntimeError('CUDA error: out of memory')
wandb: ERROR Run woy3c8cq errored: RuntimeError('CUDA error: out of memory')
wandb: Agent Starting Run: eul2ky6x with config:
wandb: 	batch_size: 13
wandb: 	criterion: cross_entropy
wandb: 	epochs: 100
wandb: 	learning_rate: 0.04379672513640217
wandb: 	model_name: cifar10_mobilenetv2_x1_4
wandb: 	momentum: 0.9
wandb: 	optimizer: nesterov
wandb: 	pretrained: False
wandb: 	scheduler: Cosine Annealing
wandb: 	transformation: models/pretrained/U_w_means_0-005174736492335796_n0-0014449692098423839_n0-0010137659264728427_and_stds_1-130435824394226_1-128873586654663_1-1922636032104492_.pt
wandb: 	use_SAM: True
wandb: 	weight_decay: 1e-05

signal only works in main thread

2021-05-25 00:58:55.852338: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-25 00:58:55.855173: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
wandb: Tracking run with wandb version 0.10.30
wandb: Syncing run quiet-sweep-3
wandb: ‚≠êÔ∏è View project at https://wandb.ai/naddeok/CIFAR10
wandb: üßπ View sweep at https://wandb.ai/naddeok/CIFAR10/sweeps/85hdflaz
wandb: üöÄ View run at https://wandb.ai/naddeok/CIFAR10/runs/eul2ky6x
wandb: Run data is saved locally in /home/naddeok5/FIM/wandb/run-20210525_005854-eul2ky6x
wandb: Run `wandb offline` to turn off syncing.
wandb: Waiting for W&B process to finish, PID 2022249
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.01MB uploaded (0.00MB deduped)wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: \ 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: | 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: / 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb:                                                                                
wandb: Find user logs for this run at: /home/naddeok5/FIM/wandb/run-20210525_005854-eul2ky6x/logs/debug.log
wandb: Find internal logs for this run at: /home/naddeok5/FIM/wandb/run-20210525_005854-eul2ky6x/logs/debug-internal.log
wandb: Run summary:
wandb:   Data Augmentation False
wandb:            _runtime 3
wandb:          _timestamp 1621918737
wandb:               _step 0
wandb: Run history:
wandb:   Data Augmentation ‚ñÅ
wandb:            _runtime ‚ñÅ
wandb:          _timestamp ‚ñÅ
wandb:               _step ‚ñÅ
wandb: 
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced quiet-sweep-3: https://wandb.ai/naddeok/CIFAR10/runs/eul2ky6x
Run eul2ky6x errored: RuntimeError('CUDA error: out of memory')
wandb: ERROR Run eul2ky6x errored: RuntimeError('CUDA error: out of memory')
Detected 3 failed runs in the first 60 seconds, killing sweep.
wandb: ERROR Detected 3 failed runs in the first 60 seconds, killing sweep.
wandb: To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true

signal only works in main thread

